version: '3'
services:

  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    # For debugging locally
    #network_mode: host
    networks:
    - app-network

  scala:
    image: quay.io/coverbeck/overbeck-backend-scala:0.0.5
    container_name: scala
    restart: unless-stopped
    tty: true
    expose:
      - "8080"
    networks:
      - app-network
    volumes:
        - ./scrape.json:/tmp/scrape.json
    environment:
      - APIKEY=${APIKEY}
      - SCRAPE_CONFIG=/tmp/scrape.json

#Docker Networks
networks:
  app-network:
    driver: bridge
