version: '3'
services:

  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    # For debugging locally
    # network_mode: host
    networks:
    - app-network

  scala:
#    image: quay.io/coverbeck/overbeck-backend-scala:0.0.9
    image: coverbeck/website-backend:latest
    container_name: scala
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
        - ./scrape.json:/tmp/scrape.json
    environment:
      - APIKEY=${APIKEY}
      - SCRAPE_CONFIG=/tmp/scrape.json
      - AMBIENT_APP_KEY=${AMBIENT_APP_KEY}
      - AMBIENT_API_KEY=${AMBIENT_API_KEY}

  postgres_db:
    image: postgres:13.3
    command: postgres -c jit=off
    container_name: postgres1
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:

#Docker Networks
networks:
  app-network:
    driver: bridge
